adobe/aepsdk-core-android

code/android-core-library/src/main/java/com/adobe/marketing/mobile/services/DeviceInforming.java, code/android-core-library/src/phone/java/com/adobe/marketing/mobile/services/DeviceInfoService.java
=> adding getOperatingSystemName to DeviceInforming

code/android-core-library/src/main/java/com/adobe/marketing/mobile/Event.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/ExtensionApi.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionContainer.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionExt.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRuleTransformer.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequence.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConstants.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesEvaluator.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/json/MatcherCondition.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/rulesengine/ConditionEvaluator.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/rulesengine/LogicalExpression.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/rulesengine/OperandFunction.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/rulesengine/OperandMustacheToken.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/rulesengine/UnaryExpression.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/MobileCoreTests.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/eventhub/EventHubTests.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/eventhub/EventListenerContainerTests.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequenceTests.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesEvaluatorTests.kt
=> Cleanup and minor updates to public APIs

code/android-core-library/src/main/java/com/adobe/marketing/mobile/Extension.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/ExtensionApi.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/SharedStateResolver.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionContainer.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/EventHistoryRequest.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/utils/DataReader.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/extensions/Sample1Kt.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/extensions/Sample2Kt.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/eventhub/EventHubTests.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionContainerJavaTests.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionContainerTests.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/utils/DataReaderTests.java
Update DataReader to throw checked exception
Add NonNull/Nullable annotations to public APIs
=> Add NonNull/Nullable annotations to public APIs

code/android-core-library/src/main/java/com/adobe/marketing/mobile/Log.java
Reverts adobe/aepsdk-core-android#186
=> Revert "Add a new parameter to Log APIs"

code/android-core-library/src/phone/java/com/adobe/marketing/mobile/AndroidSystemInfoService.java, code/android-core-library/src/phone/java/com/adobe/marketing/mobile/services/DeviceInfoService.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/AndroidSystemInfoServiceTests.java
Port change from 1.x
https://github.com/adobe/aepsdk-core-android/issues/111
=> [MOB-16865][Bug] Catch Runtime exceptions when calling PackageManager

code/android-core-library/src/phone/java/com/adobe/marketing/mobile/services/DeviceInfoService.java
=> fix return value for DeviceInfoService.getDeviceManufacturer

code/android-core-library/src/main/java/com/adobe/marketing/mobile/ExtensionApi.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/SharedStateResult.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtension.kt, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionContainer.kt, code/android-lifecycle-library/src/androidTest/java/com/adobe/marketing/mobile/TestableExtensionApi.java, code/android-lifecycle-library/src/main/java/com/adobe/marketing/mobile/lifecycle/LifecycleExtension.java, code/android-lifecycle-library/src/main/java/com/adobe/marketing/mobile/lifecycle/LifecycleV1Extension.java, code/testapp/src/androidTest/java/com/adobe/testapp/UIServicesInstrumentedTest.java, code/testapp/src/main/java/com/adobe/marketing/mobile/services/ui/TestAppUIServices.java, code/testapp/src/main/java/com/adobe/testapp/PlatformServicesFragment.java, code/testapp/src/main/java/com/adobe/testapp/UIServicesFragment.java
=> Update shared state related public APIs

code/android-core-compatiblity/src/main/java/com/adobe/marketing/mobile/AndroidFullscreenMessage.java, code/android-core-compatiblity/src/main/java/com/adobe/marketing/mobile/ContextDataUtil.java
=> fix StringUtils compatibility package issue for jitpack build failures

code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtension.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtensionTest.kt
A duplicate `dispatchConfigurationResponse()` was added as a quick fix to unlock some integration tests.
Did a clean up of a few methods after removing duplicates.
A duplicate `dispatchConfigurationResponse()` was added as a quick fix to unlock some integration tests.
Did a clean up of a few methods after removing duplicates.
=> Consolidate duplicated dispatchConfigurationResponse()

code/android-core-library/api/android-core-library.api, code/android-core-library/build.gradle
=> Update API file to fix build errors

code/android-core-library/src/phone/java/com/adobe/marketing/mobile/services/SQLiteDataQueue.java
Fix races in SQLiteDataQueue - https://github.com/adobe/aepsdk-core-android/issues/84
=> Fix races in SQLiteDataQueue

code/android-core-library/api/android-core-library.api, code/android-core-library/src/main/java/com/adobe/marketing/mobile/ExtensionHelper.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/download/RulesZipProcessingHelper.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/services/NetworkRequest.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/services/NetworkingConstants.java, code/android-core-library/src/phone/java/com/adobe/marketing/mobile/services/AppContextService.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesEngineModuleTests.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/download/RulesZipProcessingHelperTest.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/test/util/FileTestHelper.kt, code/android-core-library/src/test/java/com/adobe/marketing/mobile/test/util/TestResourceUtils.kt
https://github.com/adobe/aepsdk-core-android/issues/122
=> Add Networking constants

code/android-core-library/api/android-core-library.api, code/android-core-library/src/main/java/com/adobe/marketing/mobile/EventCoder.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/util/JSONUtils.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/util/JSONUtilsTest.java
- Add a utility class for JSON transformations
- Use the updates utility methods in EventCoder
#261 
- Unit tests
=> Add a utility class for JSON transformations

code/android-core-library/api/android-core-library.api, code/android-core-library/src/phone/java/com/adobe/marketing/mobile/MobileCore.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/MobileCoreTests.kt, code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/core/RulesEngineIntegrationTests.kt
=> Update MobileCore.registerEventListener API

code/android-core-library/api/android-core-library.api, code/android-core-library/src/main/java/com/adobe/marketing/mobile/EventSource.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/EventType.java
Add EventSource and EventType for Consent extension.
=> Add EventSource and EventType for Consent extension

code/android-core-library/api/android-core-library.api, code/android-core-library/src/main/java/com/adobe/marketing/mobile/util/DataReader.java, code/android-core-library/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageWebViewClient.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/util/DataReaderTests.java
Support for nested collection in DataReader class #274
=> Support reading list of typed maps

code/android-core-compatiblity/build.gradle, code/android-core-library/build.gradle, code/android-core-library/src/androidTest/AndroidManifest.xml, code/android-identity-library/build.gradle, code/android-lifecycle-library/build.gradle, code/android-signal-library/build.gradle, code/build.gradle, code/gradle.properties, code/gradle/wrapper/gradle-wrapper.properties
=> Updates to gradle scripts

code/android-lifecycle-library/build.gradle
Fix lifecycle extension version which is configured incorrectly for publish.
=> Fix lifecycle extension version

code/android-lifecycle-library/build.gradle, code/android-signal-library/build.gradle
=> Merge dev-v2.0.0 to staging

code/android-core-library/api/android-core-library.api, code/android-core-library/src/main/java/com/adobe/marketing/mobile/EventType.java
=> add Messaging event type

code/android-core-library/src/main/java/com/adobe/marketing/mobile/ExtensionApi.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtension.kt, code/android-core-library/src/phone/java/com/adobe/marketing/mobile/MobileCore.java, code/android-signal-library/src/main/java/com/adobe/marketing/mobile/signal/SignalExtension.kt
=> Add missing annotation to ExtensionAPI methods

code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryDatabaseTests.java, code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryTests.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryDatabase.java
Make the database name consistent with the format used within the SDK.
=> Rename event history database

docs/Usage/Identity.md, docs/Usage/Lifecycle.md, docs/Usage/MobileCore.md, docs/Usage/README.md, docs/Usage/Signal.md
Add Usage docs for MobileCore and Identity similar to [iOS repo](https://github.com/adobe/aepsdk-core-ios/tree/main/Documentation/Usage)
#280
=> Add API Usage docs

code/android-signal-library/src/main/java/com/adobe/marketing/mobile/signal/internal/EventExtensions.kt, code/android-signal-library/src/main/java/com/adobe/marketing/mobile/signal/internal/SignalConstants.kt, code/android-signal-library/src/main/java/com/adobe/marketing/mobile/signal/internal/SignalExtension.kt, code/android-signal-library/src/main/java/com/adobe/marketing/mobile/signal/internal/SignalHit.kt, code/android-signal-library/src/main/java/com/adobe/marketing/mobile/signal/internal/SignalHitProcessor.kt, code/android-signal-library/src/phone/java/com/adobe/marketing/mobile/Signal.java, code/android-signal-library/src/test/java/com/adobe/marketing/mobile/SignalAPITest.java, code/android-signal-library/src/test/java/com/adobe/marketing/mobile/signal/internal/EventExtensionsTests.kt, code/android-signal-library/src/test/java/com/adobe/marketing/mobile/signal/internal/SignalExtensionProtectedMethodsTests.kt, code/android-signal-library/src/test/java/com/adobe/marketing/mobile/signal/internal/SignalFunctionalTests.kt, code/android-signal-library/src/test/java/com/adobe/marketing/mobile/signal/internal/SignalHitProcessorTests.kt, code/android-signal-library/src/test/java/com/adobe/marketing/mobile/signal/internal/SignalHitTests.kt, code/build.gradle, code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/core/ConfigurationIntegrationTests.kt, code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/signal/SignalExtensionIntegrationTests.kt, code/microbenchmark/src/androidTest/java/com/adobe/marketing/mobile/microbenchmark/SDKInitializationBenchmark.kt
=> Move internal Signal classes into internal sub package

code/android-core-library/api/android-core-library.api, code/android-core-library/src/main/java/com/adobe/marketing/mobile/util/URLBuilder.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/util/URLBuilderTests.java, code/android-identity-library/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
Remove ssl configuration in URLBuilder util - https://github.com/adobe/aepsdk-core-android/issues/331
=> Remove ssl configuration in URLBuilder util 

code/android-core-library/api/android-core-library.api, code/android-core-library/src/main/java/com/adobe/marketing/mobile/util/MapUtils.java, code/android-core-library/src/test/java/com/adobe/marketing/mobile/util/MapUtilsTests.java
=> Make map utils more generic

code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/AndroidV4ToV5MigrationTests.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/V4ToV5Migration.java
- Migrated missing keys sessionId and edgeHost from v4 to v5
- Fixed related tests
=> Migrate missing v4 target keys to v5

code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryDatabaseTests.java, code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryDatabase.java
=> Fix 1.x EventHistory database name

code/core/src/main/java/com/adobe/marketing/mobile/InvalidInitException.java, code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionContainer.kt
=> Fix logs in Extension container

code/core/src/main/java/com/adobe/marketing/mobile/Extension.java, code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt, code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionContainer.kt, code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
=> Fix Core logs

code/identity/src/phone/java/com/adobe/marketing/mobile/Identity.java, code/lifecycle/src/phone/java/com/adobe/marketing/mobile/Lifecycle.java, code/signal/src/phone/java/com/adobe/marketing/mobile/Signal.java
=> Fix docs for deprecated methods

code/core/src/androidTest/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryDatabaseTests.java, code/core/src/androidTest/java/com/adobe/marketing/mobile/services/DataQueueServiceTests.java, code/core/src/main/java/com/adobe/marketing/mobile/internal/util/FileUtils.kt, code/core/src/main/java/com/adobe/marketing/mobile/internal/util/SQLiteDatabaseHelper.java
Handle db failures when `databases` directory was absent.
=> Handle missing parent directory for databases

Documentation/MobileCore/gradle-dependencies.md
=> Remove staging link from gradle-dependencies.md

code/core/api/core.api, code/core/src/main/java/com/adobe/marketing/mobile/services/MessagingDelegate.java, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/FullscreenMessageDelegate.java, code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ServiceProvider.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/AEPMessage.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageWebViewClient.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageWebViewRunner.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/WebViewGestureListener.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/internal/MessagesMonitor.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ServiceProviderModifier.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/AEPMessageTests.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/MessageFragmentTests.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/MessageWebViewClientTests.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/WebViewGestureListenerTests.java
=> fix inconsistencies between Android and iOS Messaging Delegate

.github/workflows/maven-release.yml, .github/workflows/maven-snapshot.yml, Makefile
=> Rename GH actions

Documentation/MobileCore/getting-started.md, Documentation/MobileCore/gradle-dependencies.md
=> Fix links and typos

code/core/api/core.api, code/core/src/main/java/com/adobe/marketing/mobile/internal/CoreConstants.kt, code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesEngine.java, code/core/src/main/java/com/adobe/marketing/mobile/rulesengine/RulesEngine.java, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/FullscreenMessage.java, code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesEngineModuleTests.kt, code/gradle.properties
- Adds "add rules" functionality to the rules engine. 
- Also fix an incorrect comment within FullscreenMessage.java.
=> Add "add rules" functionality to the rules engine

code/gradle.properties, code/identity/src/phone/java/com/adobe/marketing/mobile/Identity.java, code/identity/src/test/java/com/adobe/marketing/mobile/IdentityAPITests.java, code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityExtensionTests.kt
=> Bump Identity version to 2.0.2

code/core/release.gradle, code/core/src/main/java/com/adobe/marketing/mobile/internal/CoreConstants.kt, code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java, code/gradle.properties, code/identity/build.gradle, code/identity/src/main/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentity.java, code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java, code/identity/src/phone/java/com/adobe/marketing/mobile/Identity.java, code/identity/src/test/java/com/adobe/marketing/mobile/IdentityAPITests.java, code/identity/src/test/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentityTest.java, code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityExtensionTests.kt, code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt, code/lifecycle/build.gradle, code/sdk-bom/build.gradle, code/signal/build.gradle
* add event reference docs for core extensions (#396)
* Add a new module to build the bom artifact  (#402)
* Create bom-pr.yml
* Add a new module to build the bom artifact  (#401)
* add a new module to build the bom artifact for all extensions
* rename CI
* Update bom-pr.yml
update branch name for testing
* Update bom-pr.yml
revert changes
* address review comments
* Update gradle.properties
* Update bom-pr.yml
* Update bom-pr.yml
* remove unsupported Github action
* correct the way to get the new pom version
* Create a new CI action for sdk-bom release (snapshot builds) (#406)
* Create bom-pr.yml
* Add a new module to build the bom artifact  (#401)
* add a new module to build the bom artifact for all extensions
* rename CI
* Update bom-pr.yml
update branch name for testing
* Update …
=> Merge main -> dev

code/core/api/core.api, code/core/src/main/java/com/adobe/marketing/mobile/EventSource.java, code/core/src/main/java/com/adobe/marketing/mobile/EventType.java
Adding EventType and EventSource for Edge Media.
=> Add EventType and EventSource for Edge Media

code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
Add logging with ECID value is generated and loaded from persistence. These logs will assist in debugging ECID issues on boot.
=> Add more logging around ECID generation and loading. (resolves #432)

code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt, code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistory.java, code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/HistoricalEventsQuerying.kt
=> Fix race condition when querying historical events

code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/AEPMessage.java
=> -fix crasher on older android api versions

code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/core/ConfigurationIntegrationTests.kt
* add Edge Media EventType
* Add Edge Media EventSourcs
* Update API file
* Rename source to 'createTracker'
* Update API
=> Fix test failure in configureWithAppId

code/core/api/core.api, code/core/src/androidTest/java/com/adobe/marketing/mobile/EventCoderTests.java, code/core/src/main/java/com/adobe/marketing/mobile/Event.java, code/core/src/main/java/com/adobe/marketing/mobile/EventCoder.java, code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequence.kt, code/core/src/test/java/com/adobe/marketing/mobile/EventTests.java, code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequenceTests.kt, code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/core/RulesEngineIntegrationTests.kt, code/lifecycle/src/androidTest/java/com/adobe/marketing/mobile/lifecycle/LifecycleFunctionalTest.java, code/lifecycle/src/androidTest/java/com/adobe/marketing/mobile/lifecycle/LifecycleV2FunctionalTest.java, code/lifecycle/src/main/java/com/adobe/marketing/mobile/lifecycle/LifecycleV1Extension.java, code/lifecycle/src/main/java/com/adobe/marketing/mobile/lifecycle/LifecycleV2Extension.java, code/lifecycle/src/test/java/com/adobe/marketing/mobile/lifecycle/LifecycleV1ExtensionTest.java
- Add parentId to Event model
- Ensure inResponseToEvent sets a parentId
- Update tests
#436 
- Unit tests
- Integration tests
=> Add support for event chaining

code/core/src/main/java/com/adobe/marketing/mobile/internal/CoreConstants.kt, code/gradle.properties
=> Bump Core version to 2.2.0

code/core/api/core.api, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/FullscreenMessageDelegate.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/AEPMessage.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageFragment.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageWebViewClient.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageWebViewRunner.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageWebViewUtil.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/WebViewGestureListener.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/AEPMessageTests.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/MessageFragmentTests.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/MessageWebViewRunnerTests.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/MessageWebViewUtilTests.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/WebViewGestureListenerTests.java
=> In-app message fixes

code/sdk-bom/build.gradle
Update the BOM release scripts to:
- show sorted BOM release items
=> Improve BOM release script

code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/FloatingButtonManager.java, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/FloatingButtonManagerTests.java
=> Fix logic removing floating button and add tests

code/core/build.gradle, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/Presentable.kt, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/Presentation.kt, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/PresentationDelegate.kt, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/PresentationError.kt, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/PresentationEventListener.kt, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/PresentationLever.kt, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/PresentationListener.kt, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/PresentationUtilityProvider.kt, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/UIService.kt
- Add interfaces required for UIService API into the `vnext` subpackage of `com.adobe.mobile.marketing.services.ui`. These will later be moved to the parent package.
- Components added :
- `UIService`  - Represents a component capable of creating and managing UI elements
-  `Presentable` - Represents a component that can be presented on the screen.
-  `Presentation ` - Defines the super type of the different types of presentables that can be managed by AEP SDK. Types will be added as they are implemented.
- `PresentationDelegate ` - Delegate used to observe and control the lifecycle of presentation managed by the SDK.
- `PresentationUtilityProvider ` - Provides the necessary utilities for the UI SDK to function
- `PresentationEventListener` - Mechanism for the component that created the …
=> Add interface skeletons for UIServices

.github/workflows/update-version.yml
=> Update update-version.yml to auto delete branch

code/core/api/core.api, code/core/src/test/java/com/adobe/marketing/mobile/internal/AppResourceStoreTests.java
=> Fix build errors

code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/DefaultInAppMessageEventHandler.kt
Javascript handlers should be registered on the main thread and will take effect on the next load of the webview. InAppMessagePresentable invokes `DefaultInAppMessageEventHandler#onNewWebView()`and then later loads the url, both on the main thread. `DefaultInAppMessageEventHandler#onNewWebView()` posts the javascript handler registration again on the main thread via a coroutine. This results in the non-zero probability of loading the webview before the handler registration coroutine is executed on the main thread leading to the native callbacks failing.
Since the notification of new webview happens on the main thread, there is no need to re-post it again on main thread. This will allow execution of js handler registration and url loading serially. This PR addresses the issue with this …
=> Fix race during js handler registration

code/core/api/core.api, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/PresentationUtilityProvider.kt, code/core/src/main/java/com/adobe/marketing/mobile/util/DefaultPresentationUtilityProvider.kt, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/AEPUIService.kt, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/AEPUIServiceTest.kt, code/core/src/test/java/com/adobe/marketing/mobile/util/DefaultPresentationUtilityProviderTest.kt, code/testapp-kotlin/src/main/java/com/adobe/marketing/mobile/app/kotlin/Utilities.kt, code/testapp-kotlin/src/main/java/com/adobe/marketing/mobile/app/kotlin/uiservices/alert/AlertCreator.kt, code/testapp-kotlin/src/main/java/com/adobe/marketing/mobile/app/kotlin/uiservices/floatingbutton/FloatingButtonCreator.kt, code/testapp-kotlin/src/main/java/com/adobe/marketing/mobile/app/kotlin/uiservices/inappmessage/InAppMessageCreator.kt
UIService requires `PresentationUtilityProvider` to provide a valid application instance. Intention is for extensions to call `ServiceProvider.appContextService.getApplication()`  but ServiceProvider.appContextService.getApplication() is nullable and can return a null value if the implementer does not set the application via `MobileCore.setApplication()`. In such cases implementers of the `PresentationUtilityProvider` interface as it is currently implemented are forced to return a non-null value but cannot guarantee that. Circumvent this scenario by allowing nulls in `PresentationUtilityProvider.getApplication()` and throwing an exception in such situations without proceeding further.
N/A
UIService requires `PresentationUtilityProvider` to provide a valid application instance. Intention …
=> Allow PresentationUtilityProvider.getApplication() to return nulls

code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt
https://github.com/adobe/aepsdk-core-android/issues/552
The scheduled executor was not shutdown when EventHub was destroyed. This resource leak was causing flaky unit tests as each test runs on its own EventHub instance.
=> Shutdown scheduled job executor in event hub

code/core/src/main/java/com/adobe/marketing/mobile/V4ToV5Migration.java, code/core/src/main/java/com/adobe/marketing/mobile/VisitorID.java, code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionContainer.kt, code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryDatabase.kt, code/core/src/main/java/com/adobe/marketing/mobile/internal/util/SQLiteDatabaseHelper.java, code/core/src/main/java/com/adobe/marketing/mobile/internal/util/StringEncoder.java, code/core/src/main/java/com/adobe/marketing/mobile/internal/util/UrlEncoder.kt, code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesEngine.java, code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/download/RulesLoadResult.java, code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/download/RulesLoader.java, code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/json/GroupCondition.kt, code/core/src/main/java/com/adobe/marketing/mobile/rulesengine/MustacheToken.java, code/core/src/main/java/com/adobe/marketing/mobile/services/PersistentHitQueue.java, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/alert/AlertSettings.kt, code/core/src/main/java/com/adobe/marketing/mobile/util/CloneFailedException.java, code/core/src/main/java/com/adobe/marketing/mobile/util/DataReader.java, code/core/src/main/java/com/adobe/marketing/mobile/util/EventDataUtils.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/DeviceInfoService.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/DisplayInfoService.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/HttpConnection.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/HttpConnectionHandler.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/NetworkService.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/SQLiteDataQueue.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/ServiceProvider.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/SharedPreferencesNamedCollection.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/internal/context/App.kt, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/common/AEPPresentable.kt, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/common/AppLifecycleProvider.kt, code/core/src/phone/java/com/adobe/marketing/mobile/services/uri/UriService.kt
=> Fix lint issues

code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistory.java
=> Handle database failure when querying the event history

code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequence.kt, code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequenceTests.kt, code/core/src/test/resources/rules_module_tests/consequence_rules_testAttachData_array.json
Fixes https://github.com/adobe/aepsdk-core-android/issues/599
Ported the iOS implementation to Android https://github.com/adobe/aepsdk-core-ios/pull/988
=> [PLATIR-35300] Add array replace token support

code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java
=> Restricted the workaround code to run on specific OS versions

code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistory.kt, code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequence.kt, code/core/src/main/java/com/adobe/marketing/mobile/util/StreamUtils.java, code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java, code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequenceTests.kt, code/core/src/test/java/com/adobe/marketing/mobile/util/StreamUtilsTests.java, code/core/src/test/resources/rules_module_tests/consequence_rules_testAttachData_array.json
Cherrypick fixes made after this branch was created.
=> Cherry pick bug fixes after Core 2.5.0 

code/core/api/core.api, code/core/build.gradle.kts, code/core/src/androidTest/java/com/adobe/marketing/mobile/internal/util/NetworkUtilsTest.kt, code/core/src/androidTest/java/com/adobe/marketing/mobile/services/MockAppContextService.java, code/core/src/main/java/com/adobe/marketing/mobile/services/Networking.java, code/core/src/phone/java/com/adobe/marketing/mobile/internal/util/NetworkUtils.kt, code/core/src/phone/java/com/adobe/marketing/mobile/services/AppContextService.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/NetworkService.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/internal/context/App.kt, code/core/src/test/java/com/adobe/marketing/mobile/services/NetworkServiceTests.java, code/testapp/src/main/java/com/adobe/marketing/mobile/core/testapp/ServicesView.kt, code/testapp/src/main/java/com/adobe/marketing/mobile/core/testapp/services/NetworkServiceCard.kt, code/testapp/src/main/java/com/adobe/marketing/mobile/core/testapp/ui/inappmessage/InAppMessageCreator.kt
=> [NetworkService] check Internet availability before sending requests

code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt
**Problem** : WebView does not support rounded corners or clipping in API 21, 22. This causes the `cornerRadius` setting not to be honored in these devices.
**Solution**: Place the AndroidWebView inside a Cardview with a clipped corner radius matching the WebView and an alpha of .99f. This is the same fix that exists in [2.x UIService](https://github.com/adobe/aepsdk-core-android/blob/main/code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageWebViewUtil.java#L171)
WebView does not support rounded corners or clipping in API 21, 22. This causes the `cornerRadius` setting not to be honoured in these devices.
Place the AndroidWebView inside a Cardview with a clipped corner radius matching the WebView and an alpha of .99f.
- Manually test on Pixel 4 API 21 and API 22
=> Fix InAppMessage rounded corners for API <= 22

code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/message/views/MessageScreenTests.kt
Added some UI instrumentation tests for the following `InAppMessageSettings`
1. width
2. height
3. verticalInset
4. horizontalInset
5. verticalAlignment
6. horizontalAlignment
=> Compose instrumentation tests around IAM position and sizing

code/build.gradle.kts, code/core/build.gradle.kts, code/gradle.properties
=> Update version and gradle plugin for beta snapshot release

code/identity/build.gradle.kts, code/lifecycle/build.gradle.kts, code/signal/build.gradle.kts
Merge `dev-v3.0.0` to `staging`  for regenerating the snapshot builds with the right core dependencies in `lifecycle`, `signal` and `identity`
=> Merge `dev-v3.0.0` to `staging` 

code/build.gradle.kts, code/gradle.properties, code/identity/build.gradle.kts, code/lifecycle/build.gradle.kts, code/signal/build.gradle.kts
=> Release changes for 3.0.0

code/core/src/phone/java/com/adobe/marketing/mobile/services/DeviceInfoService.java
Media extension uses this API to check the network connection for offline scenarios. The current implementation uses deprecated APIs and so switch it to use the internal utility for consistency.
=> Update getNetworkConnectionStatus implementation to use internal utils

Documentation/Debugging.md, Documentation/MobileCore/getting-started.md
Add Kotlin examples and remove 2.x references in 3.x docs
=> Add Kotlin examples and remove 2.x references

code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistory.kt
Fixes https://github.com/adobe/aepsdk-core-android/issues/639
=> Fix event history logs

code/core/src/test/java/com/adobe/marketing/mobile/services/ui/notification/PushTemplateTypeTest.kt
Added unit tests for PushTemplateType class
JIRA : https://jira.corp.adobe.com/browse/MOB-20952
=> Push template unit test

code/core/src/test/java/com/adobe/marketing/mobile/services/ui/notification/PushTemplateTypeTest.kt
Added unit tests for PushTemplateType class
JIRA : https://jira.corp.adobe.com/browse/MOB-20952
=> Refactor unit tests for PushTemplateType

code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt, code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java, code/core/src/test/java/com/adobe/marketing/mobile/internal/eventhub/EventHubTests.kt
=> Fix strict mode violations

code/core/src/androidTest/java/com/adobe/marketing/mobile/services/DataQueueServiceTests.java, code/core/src/androidTest/java/com/adobe/marketing/mobile/services/SqliteDataQueueTests.java, code/core/src/main/java/com/adobe/marketing/mobile/internal/util/SQLiteDatabaseHelper.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/DataQueueService.java, code/core/src/phone/java/com/adobe/marketing/mobile/services/SQLiteDataQueue.java, code/core/src/test/java/com/adobe/marketing/mobile/services/SqliteDataQueueTests.java
Improve logs in `SQLiteDatabaseHelper` with database name/ path where applicable.
#585 
Improve logs in `SQLiteDatabaseHelper` with database name/ path where applicable.
=> Add database name path to logs for better visibility

code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt, code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java, code/core/src/test/java/com/adobe/marketing/mobile/internal/eventhub/EventHubTests.kt
Ported the Android 3.x change (https://github.com/adobe/aepsdk-core-android/pull/674) to 2.x to fix strict mode violations
=> Fix strict mode violations for Android 2.x

code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt
CardView has a default elevation of `1.dp` and  has a slight shadow on the background due to automatic tonal elevation color being applied by the Android system on certain light app themes.
While this is not evident when the HTML completely covers the dimension of the in-app message, it can be seen when HTML only occupies a portion of the in app message dimension.
As a solution set the elevation to `0.dp` for the CardView to prevent any shadows.
Internal MOB-21295
CardView has a default elevation of `1.dp` and  applies a slight shadow on the background.
While this is not evident when the HTML completely covers the dimension of the in-app message, it can be seen when HTML only occupies a portion of the in app message dimension.
As a solution set the elevation to `0.dp` for the CardView to …
=> Prevent CardView from applying a shadow

code/core/src/main/java/com/adobe/marketing/mobile/internal/CoreConstants.kt, code/core/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtension.kt, code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java
Standardize Event names across Android and iOS SDKs.
=> [MOB-21093] Standardize event names

code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt
=> [MOB-21325] calculate message content size after the view is placed

code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/Message.kt
Reverts adobe/aepsdk-core-android#702
=> Revert "[PLATIR-41103] Added dialog for correct screen reader case"

code/testapp/src/main/java/com/adobe/marketing/mobile/core/testapp/CoreView.kt
Make it consistent with iOS test app for easier smoke testing.
=> Update test app for smoke tests

code/core/api/core.api, code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/message/views/MessageScreenOrientationTests.kt, code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/message/views/MessageScreenTests.kt, code/core/src/main/java/com/adobe/marketing/mobile/internal/CoreConstants.kt, code/core/src/main/java/com/adobe/marketing/mobile/services/ui/message/InAppMessageSettings.kt, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageContent.kt, code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt, code/core/src/test/java/com/adobe/marketing/mobile/services/ui/message/InAppMessageSettingsTest.kt, code/gradle.properties
=> Merging main to feature/disqualification branch

code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistory.kt
=> change event history insert log level
