adobe/aepsdk-core-android

- code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/util/SerialWorkDispatcherTests.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/ExtensionContainer.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/util/SerialWorkDispatcher.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/util/URLBuilder.java
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/eventhub/EventHubTests.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/util/SerialWorkDispatcherJavaCompatTests.java
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/util/SerialWorkDispatcherTests.kt
Bug fix to reprocess events when `readyToProcess` returns false
Tests to verify `getSharedState` APIs return correct state with barrier. 
Made URLBuilder utility class public
> Bug fix to reprocess events when `readyToProcess` returns false

- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/AppIdManager.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationDownloader.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtension.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationRulesManager.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationStateManager.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/configuration/AppIdManagerTest.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationDownloaderTest.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtensionTest.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationRulesManagerTest.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationStateManagerTest.kt
Configuration extension currently passes public service instances into the constructors of internal components primarily to allow dependency injection for tests. This eager allocation prevents the default services to reflect when they are set to a custom implementation.
Remove eager service allocation in ConfigurationExtension and use ServiceProvider.getInstance().get* where required
- Unit tests
- Manual verification
> Remove eager service allocation in ConfigurationExtension

- code/android-core-compatiblity/src/main/java/com/adobe/marketing/mobile/InvalidInitException.java
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/InvalidInitException.java
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt
- code/android-core-library/src/phone/java/com/adobe/marketing/mobile/MobileCore.java
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/MobileCoreTests.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/eventhub/EventHubTests.kt
This PR contains changes to support SDK initialization for customers migrating from 1.x SDK with no compilation errors or runtime inconsistencies. 
1.x initialization code
```
try {
Analytics.registerExtension();
Edge.registerExtension();
Identity.registerExtension();
Lifecycle.registerExtension();
Signal.registerExtension();
MobileCore.start(new AdobeCallback () {
@Override
public void call(Object o) {
MobileCore.configureWithAppID("launch-EN5640fb1a17ec4f8685142ebb71e9ca3c-development");
}
});
} catch (InvalidInitException ex) {
...
}
```
Background: 
Core 2.0 added [`MobileCore.registerExtensions`](https://github.com/adobe/aepsdk-core-android/pull/161) API to simplify SDK initialization. EventHub currently initializes extensions in background thread and the caller has to call …
> Support 1.x MobileCore initialization

- code/android-core-library/api/android-core-library.api
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/EventSource.java
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/EventType.java
Adding EventType and EventSource used by Edge extensions.
Adds:
- EventType:  `EDGE_IDENTITY = "com.adobe.eventType.edgeIdentity"`
- EventSource: `RESET_COMPLETE = "com.adobe.eventSource.resetComplete"`
- EventSource: `UPDATE_IDENTITY = "com.adobe.eventSource.updateIdentity"`
> Add Edge Identity EventType and reset complete, update identity EventSources

- code/android-lifecycle-library/src/main/java/com/adobe/marketing/mobile/lifecycle/LifecycleUtil.java
- code/android-lifecycle-library/src/main/java/com/adobe/marketing/mobile/lifecycle/LifecycleV2MetricsBuilder.java
- code/android-lifecycle-library/src/main/java/com/adobe/marketing/mobile/lifecycle/XDMLifecycleEnvironment.java
- code/android-lifecycle-library/src/test/java/com/adobe/marketing/mobile/lifecycle/LifecycleUtilLocaleTest.java
- code/android-lifecycle-library/src/test/java/com/adobe/marketing/mobile/lifecycle/XDMLifecycleEnvironmentLanguageTest.java
Format the value set in the XDM field environment._dc.language to a BCP 47 style language tag.
The XDM schema for Environment requires the _dc.language field be formatted to BCP 47. The existing format used in the v2 metrics builder did not use a valid format when the locale contained script, variant, or extension codes. 
Fixes the issue by:
- When using Android API 21+, use Locale.toLanguageTag() which returns a valid BCP 47 style tag
- When using lower Android APIs, formats the language tag by using _languageCode_-_countryCode_
- Adds a validation step in XDMLifecycleEnvironment as a failsafe so only valid language tags are added to environment._dc.language.
This PR does not change the locale format in any other uses than defined above. …
> [MOB-17661] Lifecycle v2 set BCP 47 style language tag for XDM field environment._dc.language

- code/android-core-library/api/android-core-library.api
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/EventSource.java
`com.adobe.eventSource.removeIdentity` is missing from the EventType constants. Add it so that it can be used in EdgeIdentity.
N/A
`com.adobe.eventSource.removeIdentity` is missing from the EventType constants. Add it so that it can be used in EdgeIdentity.
N/A - Just added a constant.
> Add EventSource.REMOVE_IDENTITY

- code/android-core-library/api/android-core-library.api
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchTokenFinder.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/util/TimeUtils.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/util/TimeUtilsTests.java
This PR refactors the existing `TimeUtils` to use a public `enum` system with a set of available date formatting patterns (the current set is pulled from the existing private formatting strings).
Both ISO 8601 helper methods have updated names to better reflect their return values, and both are able to accept an optional `Date` arg to convert using the specified pattern.
`getIso8601Date` -> `getIso8601DateTimeZoneRFC822` 
* There is value in being more specific with the time zone formatting this method uses, as it will reduce potential ambiguity, and this naming convention aligns with the next method:
`getIso8601DateTimeZoneISO8601` -> `getIso8601DateTimeZoneUTC` 
* The "TimeZoneISO8601" is not as clear as "TimeZoneUTC" because ISO 8601 is the general date pattern standard, with many …
> TimeUtils Refactor

- code/android-signal-library/build.gradle
Signal library should use the publish version based on the type of the build. Fix the publish based on `isReleaseBuild()`
> Fix the version of Signal library artifact

- code/android-core-library/src/main/java/com/adobe/marketing/mobile/services/PersistentHitQueue.java
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/services/PersistentHitQueueTests.java
All threads and executors maintained by core should be relinquished when not in use. Shutdown PersistentHitQueue ScheduledExecutorService on close(). 
#321
> Shutdown PersistentHitQueue ScheduledExecutorService on close()

- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtension.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationStateManager.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtensionTest.kt
Configuration extension erroneously uses a shorter time delays i.e milliseconds when seconds should be used so the wait times end up being 15 milliseconds and 5 milliseconds when they actually should be 15 seconds and 5 seconds.
> Fix delay values in config extension

- code/android-core-library/api/android-core-library.api
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/util/JSONUtils.java
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/util/MapUtils.java
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/util/JSONUtilsTest.java
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/util/MapUtilsTests.java
Convenience JSONUtils and MapUtils used by multiple extensions.
> New JSONUtils and MapUtils

- code/android-core-library/api/android-core-library.api
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/ExtensionHelper.java
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventPreprocessor.kt
- code/android-core-library/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesEvaluator.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtensionTest.kt
- code/android-core-library/src/test/java/com/adobe/marketing/mobile/internal/eventhub/EventHubTests.kt
Making `EventPreprocessor` non public as we don't expose API for extensions to set preprocessor. We can explore later around exposing preprocessor logic.
> Make EventPreprocessor non public

- code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistory.java
Use lazy executor initialization for AndroidEventHistory so that a thread pool is not initialized when not in use.
> Use lazy executor initialization for AndroidEventHistory

- code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
- code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityHitsProcessing.java
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityExtensionTests.kt
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityFunctionalTests.kt
1. There are cases when Identity will create an initial shared state using “null” twice when booting. The iOS implementation has a check for this which I’ll need to add to the Android implementation.
2. On privacy toggle or a call to resetIdentities, a force sync event is dispatched to the Event Hub which when processed will generate a new ECID. This can cause a delay where, if any other events are already in the queue will get processed without an ECID. iOS calls syncIdentifiers directly here to ensure the ECID is generated when resetIdentities is processed. I’ll make that change to Android as well.
> Ensure initial shared state is created once and sync new ECID immediately after reset

- README.md
Fix broken link to `getting-started.md` in Readme
> Fix broken link to getting-started.md

- code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityExtensionTests.kt
- code/integration-tests/build.gradle
- code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt
Fixes issue where appendToUrl/urlVariables blocks on Analytics shared state even when Analytics is not registered.
Unit tests, integration tests and sample app.
> Fix issue where appendToUrl/urlVariables blocks on Analytics

- code/core/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtension.kt
- code/core/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtensionTest.kt
- code/integration-tests/build.gradle
- code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt
The response type for Config requestIdentity should be responseIdentity.
For now the testGetSdkIdentities integration test is still ignored, pending fix in Analytics extension.
Unit and integration tests
> Fix response type for config requestIdentity

- code/core/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtension.kt
- code/core/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtensionTest.kt
Currently when a configuration download fails, a retry job is expected to be dispatched after 5 seconds. However the job is erroneously being dispatched after 5000 seconds. Fix the time units for the dispatch job.
Currently when a configuration download fails, a retry job is expected to be dispatched after 5 seconds. However the job is erroneously being dispatched after 5000 seconds. Fix the time units for the dispatch job.
- Unit tests
- Manual test after simulating an network outage
> Fix time unit for configuration retry

- code/core/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationDownloader.kt
- code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/download/RulesLoader.java
- code/core/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationDownloaderTest.kt
- code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/download/RulesLoaderTest.java
- code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityHitsProcessing.java
- code/signal/src/main/java/com/adobe/marketing/mobile/signal/internal/SignalHitProcessor.kt
- code/signal/src/test/java/com/adobe/marketing/mobile/signal/internal/SignalHitProcessorTests.kt
After any nework request the connection needs to be closed to ensure that the resource streams do not leak.
After any network request the connection needs to be closed to ensure that the resource streams do not leak.
#382 
- Unit tests 
- Manual tests using `testapp-kotlin`
> Close connection after network requests

- code/core/src/main/java/com/adobe/marketing/mobile/internal/CoreConstants.kt
- code/gradle.properties
- code/identity/src/phone/java/com/adobe/marketing/mobile/Identity.java
- code/identity/src/test/java/com/adobe/marketing/mobile/IdentityAPITests.java
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityExtensionTests.kt
- code/lifecycle/src/phone/java/com/adobe/marketing/mobile/Lifecycle.java
- code/lifecycle/src/test/java/com/adobe/marketing/mobile/lifecycle/LifecycleExtensionTest.java
- code/signal/src/phone/java/com/adobe/marketing/mobile/Signal.java
- code/signal/src/test/java/com/adobe/marketing/mobile/SignalAPITest.java
- code/signal/src/test/java/com/adobe/marketing/mobile/signal/internal/SignalExtensionProtectedMethodsTests.kt
Currently when a configuration download fails, a retry job
is expected to be dispatched after 5 seconds. However the
job is erroneously being dispatched after 5000 sconds.
Fix the time units for the dispatchj job.
> Update versions to 2.0.1

- code/core/release.gradle
- code/identity/build.gradle
- code/lifecycle/build.gradle
- code/sdk-bom/build.gradle
- code/signal/build.gradle
The POM reference gives a clear definition of the license section in a POM file => https://maven.apache.org/pom.html#Licenses 
```
<licenses>
<license>
<name>Apache-2.0</name>
<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
<distribution>repo</distribution>
<comments>A business-friendly OSS license</comments>
</license>
</licenses>
```
We are now only including the name section in our POM file. Some artifact license validation tools will not understand which license our artifacts are using because of the missing license url section. For more information, please see this issue report (https://github.com/adobe/aepsdk-core-android/issues/415).
Here are POM examples from other open-source artifacts:
- kotlin-stdlib (https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1 …
> Add license url and distribution sections to the POM file

- code/identity/src/main/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentity.java
- code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentityTest.java
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityExtensionTests.kt
- code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt
Currently, Identity uses the first set Configuration shared state when processing the force sync during boot up. This causes issues when the first Configuration is not valid. Instead, the Identity boot sequence should use the last set Configuration shared state when processing the force sync event. This way, if the first set Configuration state is invalid, then the next set Configuration state can be used to initialize the Identity extension.
- Refactor `readyForSyncIdentifiers` to take in a Map of the configuration state instead of getting the configuration state from an Event. In addition, update the `latestValidConfig` if the configuration state contains a `experienceCloud.org` value. This is similar to the iOS Swift implementation.
- Update `forceSyncIdentifiers` to use the refactored …
> Use latest configuration on Identity bootup (resolves #414)

- code/core/release.gradle
- code/core/src/main/java/com/adobe/marketing/mobile/internal/CoreConstants.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java
- code/gradle.properties
- code/identity/build.gradle
- code/identity/src/main/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentity.java
- code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
- code/identity/src/phone/java/com/adobe/marketing/mobile/Identity.java
- code/identity/src/test/java/com/adobe/marketing/mobile/IdentityAPITests.java
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentityTest.java
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityExtensionTests.kt
- code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt
- code/lifecycle/build.gradle
- code/sdk-bom/build.gradle
- code/signal/build.gradle
Merge to staging for Core 2.1.1 and Identity 2.0.2 releases:
- Core: Fix application crash when Core boots.
- Identity: Fix issue where Identity extension does not boot when initial Configuration does not contain a valid Experience Cloud organization ID.
- Add Apache license URL to POM
> Merge to Staging for Core v2.1.1 Identity v2.0.2 release

- code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchTokenFinder.kt
Removes debug log for a common path for Rules Engine, reducing overall logs verbosity. Currently if multiple rules and data elements are enabled it can easily swamp the logs when processing each event.
> Reduce rules verbosity for common path

- code/core/src/main/java/com/adobe/marketing/mobile/internal/util/MapExtensions.kt
- code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/HistoricalEventsQuerying.kt
- code/core/src/test/java/com/adobe/marketing/mobile/internal/util/MapUtilsTests.java
- code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/json/JSONConditionTests.kt
- fix searchType logic within the HistoricalEventsQuerying. if we have search type == any, we don't want to do an ordered search.
- fix fnv1a hash creation within MapExtensions. we want to check for empty map values (null or empty string) and not include them when creating the hash.
> Event history fixes

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/AEPMessage.java
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageFragment.java
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageWebViewRunner.java
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/AEPMessageTests.java
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/MessageFragmentTests.java
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/MessageWebViewRunnerTests.java
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/WebViewGestureListenerTests.java
Create the WebView object prior to passing the AEPMessage object to the MessagingDelegate. This allows the WebView to be available before the MessagingDelegate.shouldShowMessage function gets called. This matches the behavior on the iOS side and allows javascript code present in the in-app html to access javascript handlers set on the WebView.
> Create WebView object prior to passing the AEPMessage object to the MessagingDelegate to resolve WebView javascript handler issues

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/AEPMessage.java
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageFragment.java
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageWebViewUtil.java
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/AEPMessageTests.java
This is a replica of #480 with some modifications
to increase chances of showing a message.
- Handle FragmentManager exceptions gracefully.
- Fix corner rounding for AEPMessages. When the switch to DialogFragment was made, using a CardView alone was no longer sufficient to set rounded corners on the CardView. Use GradientDrawable in conjunction with CardView to set the rounded corners.
> In-app fixes from #480

- code/build.gradle
- code/core/api/core.api
- code/core/build.gradle
- code/core/release.gradle
- code/gradle.properties
- code/identity/build.gradle
- code/integration-tests/build.gradle
- code/lifecycle/build.gradle
- code/macrobenchmark/build.gradle
- code/microbenchmark/build.gradle
- code/signal/build.gradle
- code/test-third-party-extension/build.gradle
- code/testapp-kotlin/build.gradle
- code/testapp/build.gradle
UIServices provided by `aepsdk-core-android` will now move to Jetpack Compose based UI. To start with this migration uplevel current language and gradle dependencies to ones that support Compose. [Jetpack needs Kotlin 1.5+](https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility) and is supported on [minSdk versions 21+](https://developer.android.com/jetpack/compose/setup#create-new)
- Change `minSdk` requirement from `API 19` to `API 21`.
- `Android Gradle Plugin 7.3.1` needs at least `Kotlin 1.5.21`. However, `1.5.21` results in incompatibility issues with Android Studio Flamingo onwards. So use `1.5.31` instead.
- Use the mapping between Compose Compiler version and Kotlin version …
> Update Android minSDK and Kotlin version to adopt Jetpack Compose [MOB-18949]

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/AndroidUIService.java
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/AndroidUIServiceTests.java
A ClassCastException was occurring because the local notification user info map was unmodifiable. To resolve this, a HashMap copy of the local notification user info map should be made instead of casting the existing user info map to a HashMap.
Internal JIRA: MOB-19323
> fix map casting exception when attempting to show a local notification

- code/core/api/core.api
- code/core/src/main/java/com/adobe/marketing/mobile/EventSource.java
Adds EventSource 'com.adobe.eventSource.contentComplete' used in Edge workflows to signal that a request connection is closed and no further response handles will be dispatched. 
Needed for issue https://github.com/adobe/aepsdk-edge-android/issues/77.
> Add EventSource 'contentComplete' for Edge workflows

- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/Presentation.kt
- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/PresentationEventListener.kt
- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/UIService.kt
- UIService#create(..) can accept Presentation<T> instead of a wildcard
- Change PresentationEventListener<T : Presentable<*>> to
PresentationEventListener<T : Presentation<T>>
#525 
Improve signatures of the public interfaces for UI Services
> Update UI Interfaces with better generic signatures

- code/core/src/main/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationStateManager.kt
- code/core/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationStateManagerTest.kt
Calling MobileCore.updateConfiguration() will update the exact key match for environment prefixed keys. Meaning, calling `MobileCore.updateConfiguration(mapOf("analytics.rsids" to "mynew.rsid"))` will update the `"analytics.rsids"` value instead of the `"__dev__analytics.rsids"` value when the environment is "dev".
Calling `MobileCore.updateConfiguration()` should update the current environment's configuration key instead of exact key matches, similar to the iOS implementation.
Map the config keys provided during `MobileCore.updateConfiguration()` to their environment aware values before updating/merging the configuration.
This PR also updates the ConfigurationTests to be independent to the method being tested.
#539 
- Unit tests
- Manual tests with testapp-kotlin
> Make updateConfiguration API environment aware

- code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/vnext/alert/views/AlertScreenTests.kt
- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/Presentation.kt
- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/alert/AlertEventListener.kt
- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/alert/AlertSettings.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/vnext/AEPUIService.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/vnext/alert/AlertPresentable.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/vnext/alert/views/AlertScreen.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/vnext/alert/views/AlertTestTags.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/vnext/alert/AlertSettingsTest.kt
This PR adds support for Alert UI in UIServices vNext.
- Added an Alert presentation type that accepts AlertSettings and AlertEventListener.
- AlertScreen is the visual component of the Alert.
- Add tests for settings and composable. Presentable tests will be added with all other presentable integration tests in the test app.
Note that the co-ordination between Alert and InAppMessage will be added as part of #530 
#531 
UIServices vNext needs Alert UI support. Add support using Jetpack AlertDialog.
- Unit tests
- Functional Tests
> Add support for Alert UI

- code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java
- code/core/src/test/java/com/adobe/marketing/mobile/internal/AppResourceStoreTests.java
Included a new API in MobileCore - `getSmallIconResourceID` that returns the smallIconRescourceID, if it has already been set using API `MobileCore.setSmallIconResourceID`
This API will be used by AJO (Messaging extension's) notification builder to use the small Icon that is set in MobileCore.
Unit tests + Manual testing
> Expose getSmallIconResourceID API for AJO Notification Builder

- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/vnext/PresentationError.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/vnext/common/AEPPresentable.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/vnext/common/AEPPresentableTest.kt
Presentable operations can fail due to a few reasons. The PresentationEventListeners should be notified when these cases arise. This PR adds support for error notifications.
Add ShowFailed, HideFailed, DismissFailed error types and invoke listeners where appropriate.
#534 
- Unit tests
> Adds support for error notifications to PresentationEventListeners

- code/core/src/phone/java/com/adobe/marketing/mobile/services/uri/UriService.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/uri/UriServiceTest.kt
ServiceProvider instantiates UriService but UriService also currently needs ServiceProvider to get AppContextService.
Fix curcularity by using ServiceProvider on demand in UriService instead of a member variable.
N/A
ServiceProvider instantiates UriService but UriService also currently needs ServiceProvider to get AppContextService.
Fix curcularity by using ServiceProvider on demand in UriService instead of a member variable.
- Unit test
> Fix circular link b/w ServiceProvider and UriService

- code/core/src/main/java/com/adobe/marketing/mobile/util/StreamUtils.java
- code/core/src/test/java/com/adobe/marketing/mobile/util/StreamUtilsTests.java
`StreamUtils.readAsString()` does not close the input and output streams after reading them resulting in a resource violation in StrictMode when processing downloaded Configuration. Ensure that the resources are wrapped in try with resource block and a finally block as appropriate.
#571 
`StreamUtils.readAsString()` does not close the input and output streams after reading them resulting in a resource violation in StrictMode. Ensure that the resources are wrapped in try with resource block and a finally block as appropriate.
- Manual test
- Enable strict mode in testapp-kotlin  with process death penalty and do a fresh install run and a re-launch of the app to verify that process does not crash.
> Ensure resources are closed after use in StreamUtils

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageFragment.java
- Resolves a crash reported in PLATIR-33369. To fix the crash, null checks have been added to verify that the message object is non null before accessing member methods.
> PLATIR-33369: Resolve MessageFragment crash

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageContent.kt
Currently the `WebView` that renders the InAppMessage is wrapped inside an `AndroidView` composable. Leaving it as is is causing HTML's with "overflow" based CSS manipulation to render incorrectly. The is likely due to the xml based `WebView` not honoring the `Modifier` of `AndroidView`.
As a solution, this PR explicitly makes the WebView to match the dimensions of the AndroidView that wraps it. This allows fixing the bounds of the webview and overflow.
N/A
Target uses HTML's that have overflow based css manipulation which is not being rendered correctly. Fix it by forcing WebView bounds to match AndroidView dimensions.
- Manual test with a target html that caused the problem.
> Force WebView bounds to match AndroidView dimensions

- code/core/api/core.api
- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/MessageSettings.java
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/MessageFragment.java
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/WebViewGestureListener.java
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/MessageFragmentTests.java
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/WebViewGestureListenerTests.java
The UI takeover setting was incorrectly implemented on Android. If UI takeover is disabled, taps occurring outside of the in-app webview were dismissing the message. This pr updates the behavior to allow the taps to interact with the underlying app UI if UI takeover is disabled. Additionally, the decor view background will not be dimmed.
> Fix UI takeover behavior

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/AEPMessage.java
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/AEPMessageTests.java
- code/testapp/src/main/java/com/adobe/marketing/mobile/services/ui/TestAppUIServices.java
- code/testapp/src/main/java/com/adobe/testapp/UIServicesFragment.java
Also fixed the test app to actually display a dismissible message.
> [PLATIR-34650] Fix IAM bug causing webview creation failure from blocking ui

- code/core/api/core.api
- code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/message/views/MessageScreenTests.kt
- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/message/InAppMessageSettings.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/mapping/MessageAnimationMapper.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageBackdrop.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/message/GestureTrackerTest.kt
- code/testapp/src/main/java/com/adobe/marketing/mobile/core/testapp/ui/inappmessage/InAppMessageCreator.kt
To ensure consistency with iOS and IAM payload values, update `backgroundTap` to `tapBackground` within the MessageGesture enum.
> Rename backgroundTap to tapBackground in MessageGesture enum

- code/core/build.gradle.kts
- code/core/src/main/java/com/adobe/marketing/mobile/internal/util/ActivityCompatOwner.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/common/AEPPresentable.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/common/ActivityCompatOwner.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/common/AEPPresentableTest.kt
ComposeView requires a lifecycle owner  when attaching to a view and not finding one will result in a crash.
`android.app.Activity`, which is the base class in the framework package, does not provide a lifecycle owner by default.
`android.app.Activty` has not been updated for a long time and Android created `AppCompatActivity`/`FragmentActivity` in the support package to allow updates to be compatible with old android devices. Android [recommends](https://developer.android.com/topic/libraries/support-library#framework-apis) using inheriting from `AppCompatActivity` or similar which provides a lifecycle owner by default (irrespective of whether compose is being used or not).
There may be cases where apps still use this legacy Activity in their apps and launching our Ui Service components …
> Fix crash during composable attachment to android.app.Activity

- code/core/src/test/java/com/adobe/marketing/mobile/services/NetworkServiceTests.java
- code/signal/src/main/java/com/adobe/marketing/mobile/signal/internal/SignalExtension.kt
- code/signal/src/main/java/com/adobe/marketing/mobile/signal/internal/SignalHitProcessor.kt
- code/signal/src/test/java/com/adobe/marketing/mobile/signal/internal/SignalFunctionalTests.kt
- code/signal/src/test/java/com/adobe/marketing/mobile/signal/internal/SignalHitProcessorTests.kt
- code/testapp/src/main/java/com/adobe/marketing/mobile/core/testapp/SignalView.kt
- The Signal extension is updated to adopt the network service changes added in Android Core 3.0.0. (https://github.com/adobe/aepsdk-core-android/pull/612) 
- The test app has been updated for manual testing behaviors of the Signal extension when the device's network is on and off.
The test cases mentioned below have been tested on both the Android device and emulator.
1. When the device's network is online, the Signal extension can send `post back` requests correctly. 
2. When the device's network is offline, `post back` requests were queued, and there was no network connection established (monitored through Android Stidio's network inspector view) 
3. The queued requests were sent out correctly after the device's network was back online. 
4. New requests can be sent out immediately if …
> [Android 3.0.0] Adopt the network service changes in Signal

- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/message/InAppMessageSettings.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/mapping/MessageOffsetMapper.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/message/InAppMessageSettingsTest.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/message/mapping/MessageOffsetMapperTest.kt
Currently, InAppMessages use the horizontal and vertical insets from in-app message settings as padding values. However, the intended behavior is that the insets act as offsets relative to the alignment and screen dimensions.
Fix the behavior based on the spec and production behavior
MOB-20535
Currently, InAppMessages use the horizontal and vertical insets from in-app message settings as padding values. However, the intended behavior is that the insets act as offsets relative to the alignment and screen dimensions.
Fix the behavior based on the spec and production behavior
> Fix InAppMessage inset behavior

- code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
- code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityHitsProcessing.java
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityFunctionalTests.kt
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityHitsProcessingTests.kt
The Identity extension is updated to adopt the network service changes added in Android Core 3.0.0. (https://github.com/adobe/aepsdk-core-android/pull/612) 
The test cases mentioned below have been tested on both the Android device (API level 34) and the emulator (API level 21/34).
1. When the device’s network is **online**, call `setPushIdentifier` API multiple times and check the requests are sent out correctly. (monitored through Android Studio’s network inspector view)
2. When the device’s network is **offline**, call `setPushIdentifier` API multiple times (requests should be queued), and there is no network connection established (monitored through Android Studio’s network inspector view)
3. The queued requests are sent out correctly after the device’s network is back **online**.
4. …
> [Android 3.0.0] Adopt the network service changes in Identity

- code/identity/build.gradle.kts
- code/lifecycle/build.gradle.kts
- code/signal/build.gradle.kts
Publish Lifecycle, Signal, Identity use the `coreExtensionVersion` to publish dependencies in POM. 
`addCoreDependency()`  from the aep-library plugin being [used inside the ](https://github.com/adobe/aepsdk-userprofile-android/blob/dev-v3.0.0/code/userprofile/build.gradle.kts#L14) `build.gradle.kts` for extensions do not have a way to know that the current build variant being built. So the SNAPSHOT  suffix is not being added to dependancies
Use "$coreExtensionVersion-SNAPSHPOT" instead.
Publish Lifecycle, Signal, Identity use the `coreExtensionVersion` to publish dependencies in POM. 
`addCoreDependency()`  from the aep-library plugin being [used inside the ](https://github.com/adobe/aepsdk-userprofile-android/blob/dev-v3.0.0/code/userprofile/build.gradle.kts#L14) `build.gradle.kts` for …
> Publish Lifecycle, Signal, Identity with `core:3.0.0.beta.1-SNAPSHOT` dependancies

- code/core/src/main/res/layout/push_template_auto_carousel.xml
- code/core/src/main/res/layout/push_template_carousel_item.xml
- code/core/src/main/res/layout/push_template_collapsed.xml
- code/core/src/main/res/layout/push_template_expanded.xml
- code/core/src/main/res/layout/push_template_filmstrip_carousel.xml
- code/core/src/main/res/layout/push_template_manual_carousel.xml
- code/core/src/main/res/values/dimens.xml
- code/core/src/main/res/values/styles.xml
- in addition, reduce skip left and skip right size by 50%
- details and screenshots can be seen in https://github.com/adobe/aepsdk-campaignclassic-android/pull/74
> port fixes from ACC 2.1.6: support mutliple lines of text and fix widescreen image cropping in carousel templates

- .github/workflows/maven-release.yml
- code/core/src/main/java/com/adobe/marketing/mobile/DataMarshaller.java
- code/core/src/main/java/com/adobe/marketing/mobile/internal/CoreConstants.kt
- code/core/src/test/java/com/adobe/marketing/mobile/MobileCoreTests.kt
- code/core/src/test/java/com/adobe/marketing/mobile/internal/configuration/ConfigurationExtensionTests.kt
- code/gradle.properties
https://developer.android.com/reference/android/os/BaseBundle#get(java.lang.String)
As reported by the customer, the above Android API used in [DataMarshaller.java](https://github.com/adobe/aepsdk-core-android/blob/main-v2/code/core/src/main/java/com/adobe/marketing/mobile/DataMarshaller.java#L128) throws ClassNotFound exceptions in certain cases. Catch those exceptions to avoid app crashes.
> Catch exceptions when retrieving data from Activity

- code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/message/views/MessageScreenTests.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageContent.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt
**Problem**: Currently, InAppMessages with content overflowing the bounds are not scrollable even when gestures are disabled. This is because the `draggable` effect on the AndroidView that hosts the WebView is conflicting with the WebViews scroll (`isHorizontalScrollEnabled`, `isVerticalScrollEnabled`).
**Solution**: Apply gesture detection on the frame of the WebView i.e the Card inside the `MessageFrame` and ensure that it is enabled only if gestures are not available.
Also fixed deprecated usage of `performGesture` with `performTouchInput`
#638 
- Manual test with test app.
- Jetpack test suite does not support scroll verification, the swipe verification instrumented tests pass.
-  No gestures defined + swipe/scroll on in-app message => scrolls webveiw
- Gestured defined + swipe + …
> Fix InAppMessage Scrolling

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/InAppMessagePresentable.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/uri/UriService.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/message/InAppMessagePresentableTest.kt
Currently, presentation delegate notifies only the url's opened by the UriService - which is a regression from 2.x (where all successfully opened URI's were notified)
As a solution change the logic to make UiService handle both uri's and url's if the event listener is unable to handle them. Further, notify PresentationDelegate of all uri's opened as part of the interaction.
- Update `handleInAppUri` to `handleInAppUri`
- Remove url validation because we now handle all URI's (handled by UriService)
- Add tests
(Internal) MOB-20924
Currently, presentation delegate notifies only the url's opened by the UriService which is a regression from 2.x.
Change the logic to make UiService handle both uri's and url's if the event listener is unable to handle them. Further, notify PresentationDelegate …
> Notify PresentationDelegate on all webview uri's

- code/core/build.gradle.kts
- code/core/src/androidTest/AndroidManifest.xml
- code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/RestrictedConfigActivity.kt
- code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/message/views/MessageScreenOrientationTests.kt
- code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/message/views/MessageScreenTestHelper.kt
- code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/message/views/MessageScreenTests.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/floatingbutton/views/FloatingButton.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageContent.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt
**Problem**: Currently, screen size related calculations are done once and remembered on recompositions. This works well generally when adapting to the new size when orientation of the device is changed.
However, when the activity hosting the composable restricts configuration change (via `android:configChanges="orientation|..."` flags in the activity manifest), the remembered value is not recomputed preventing the presentables from adapting to the new screen size.
**Solution**: Do not remember the size related calculations. Always calculate them on composition.
- Rename current orientation test to reflect that they test configuration
-  Add UiAutomator as an android test dependency and simulate rotation using and test using config restricted activity.
Internal (MOB-20923)
- Manual tests …
> Always recompute screen size related calculations

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/notification/PushTemplateImageUtil.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/notification/PushTemplateImageUtils.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/notification/builders/AEPPushNotificationBuilder.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/notification/builders/AutoCarouselNotificationBuilder.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/notification/builders/BasicNotificationBuilder.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/notification/builders/ManualCarouselNotificationBuilder.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/notification/extensions/NotificationCompatBuilderExtensions.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/notification/extensions/RemoteViewsExtensions.kt
- Changes `PushTemplateImageUtil` to use `NetworkService` for downloading images.
- Since multiple async requests for each image download are spawned at the same time, added a `CountDownLatch` to wait for all requests to complete.
- `download` method only return number of images downloaded to avoid holding bitmaps in memory. The images can be fetched from cache if/when needed using `getImageFromCache`
> Change push template image download to use NetworkService

- code/lifecycle/src/androidTest/java/com/adobe/marketing/mobile/lifecycle/LifecycleFunctionalTest.java
- code/lifecycle/src/androidTest/java/com/adobe/marketing/mobile/lifecycle/LifecycleV2FunctionalTest.java
- code/lifecycle/src/main/java/com/adobe/marketing/mobile/lifecycle/LifecycleUtil.java
- code/lifecycle/src/main/java/com/adobe/marketing/mobile/lifecycle/LifecycleV2Extension.java
- code/lifecycle/src/main/java/com/adobe/marketing/mobile/lifecycle/LifecycleV2MetricsBuilder.java
- code/lifecycle/src/test/java/com/adobe/marketing/mobile/lifecycle/LifecycleV2ExtensionTest.java
The lifecycle v2 extension detects app upgrades by comparing the stored `app version name` string with the current one. To improve detection accuracy, the system now updates to use the full version string in the format of `<version number> (<version code>)`, which matches how the app version is displayed in XDM objects.
To ensure consistency across platforms, we can release this change simultaneously for both the iOS and Android SDKs. We can merge this PR at a later time, once we have decided on the release date.
> Lifecycle v2 enhancement (app upgrade)

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/AEPUIService.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/alert/AlertPresentable.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/common/AEPPresentable.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/floatingbutton/FloatingButtonPresentable.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/InAppMessagePresentable.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/alert/AlertPresentableTest.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/floatingbutton/FloatingButtonPresentableTest.kt
Currently AEPUIService creates a coroutine scope for every presentable to avoid one workflow distuption cancelling another.
Instead we can use a combination of SupervisorJob and a Coroutine execption handler to use the same coroutine scope for all operations on main thread by UIService, while ensuring that the disjoint interactions do not interfere with each other.
This way we prevent the app crashing if some runtime exception happens un ui-service, listeners or handlers while also creating one scope that lives through the course of the application instead of several.
N/A
- Run default test suite and manual tests
> Use a supervisor job and exception hander in UIService

- code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityExtensionTests.kt
- code/identity/src/test/java/com/adobe/marketing/mobile/identity/IdentityFunctionalTests.kt
Updates the Identity extension to not dispatch the `AnalyticsForIdentityRequest` event when privacy status is changed to optedout.
The Identity extension is expected to dispatch the `AnalyticsForIdentityRequest` event when the push identifier changes or when push tracking is denied the first time. This event tells Analytics to dispatch an ADBINTERNAL:Push event with `a.push.optin` value of either `True` or `False`. The issue is in some cases changing the privacy status to `optedout` would trigger a dispatch of the `AnalyticsForIdentityRequest` event even though `setPushIdentifier` was never called.
This fix changes how Identity handles processing of an privacy status change to `optedout` by clearing the push token and flags instead of calling `updatePushIdentifier` with nil, which would …
> Identity don't dispatch Analytics push event on privacy change

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt
The InAppMessage WebView is hosted inside a `Card` container. By default the `Card` background color is grey. This is causing unintended results(grey bg being seen) for  in-app messages where dimensions are set to fill the entire screen but the content only occupies a portion of it.
As a solution, set the container Card's background color to Color.Transparent as with the WebView.
Internal (MOB-21133)
The InAppMessage WebView is hosted inside a `Card` container. By default the `Card` background color is grey. This is causing unintended results(grey bg being seen) for  in-app messages where dimensions are set to fill the entire screen but the content only occupies a portion of it.
As a solution, set the container Card's background color to Color.Transparent as with the WebView.
- Test app …
> Set in-app web view container background to be transparent

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/common/AEPPresentable.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/common/AEPPresentableTest.kt
Currently, the `ComposeView` attached to the `Activity` when presentables are shown is not removed until the activity is destroyed. This is OK for most use-cases that follow the single window mode where the newly resumed activity obscures the previous one, and the presentable redraws on the new activity. 
However, this approach of waiting until the activity is destroyed may result in the presentables being shown on each activity in a multi-window side-by-side mode.
While we do not support multi-window mode, we should ensure that the experience does not deteriorate in such a case. As a solution, change the current detachment logic to to the following:
1.  Track the current activity that the presentable is attached to
2. When presentable is visible on `ActivityA` and another activity …
> Detach presentables before re-attaching to top Activity

- code/core/build.gradle.kts
- code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java
- code/core/src/test/java/com/adobe/marketing/mobile/MobileCoreRobolectricTests.kt
- code/testapp/src/main/AndroidManifest.xml
- code/testapp/src/main/java/com/adobe/marketing/mobile/core/testapp/BootBroadcastReceiver.java
- code/testapp/src/main/java/com/adobe/marketing/mobile/core/testapp/MyApp.kt
- Added logic to prevent the SDK from initializing in Android direct boot mode to avoid app crashes. 
- Updated the test app to allow running in Android direct boot mode.
- After rebooting the device, it is running in direct boot mode before unlocking the screen.
- SDK is not initialized and extensions are not registered.
- After the device is unlocked, the EventHub singleton is initialized. However, the API calls are dropped since extensions are not registered correctly. 
Device is locked:
Device is unlocked:
Calling public APIs will cause the MobileCore.dispatch() method to be triggered, which will subsequently [initiate](https://github.com/adobe/aepsdk-core-android/blob/main/code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java#L282) the EventHub singleton. 
``` …
```
> Do not initialize SDK in direct boot mode

- code/core/api/core.api
- code/core/src/main/java/com/adobe/marketing/mobile/EventSource.java
- code/core/src/main/java/com/adobe/marketing/mobile/util/EventUtils.kt
- code/core/src/test/java/com/adobe/marketing/mobile/util/EventUtilsTest.kt
The SDKs often needs to change its standard business logic to enable debugging/testing workflows. We need an event structure that external systems can follow to generate an event that communicates to the listening SDK extension that it should operate in a debug mode - a mode outside of expected production behavior if one exists.
This commit adds an eventSource "com.adobe.eventSource.debug" to identify such events.
Further, it adds utility methods to identify the eventType and eventSource provided within the `data.debug` content of such events.
**Structure:**
```
{
"name" : "......",
"type" : "com.adobe.eventType.system",
"source" : "com.adobe.eventSource.debug",
"data" : {
"debug": {
"eventType": "<DEBUG_EVENT_TYPE>",
"eventSource": "<DEBUG_EVENT_SOURCE>"
},
"someOtherKey":  {
....
}
}
} …
```
> Add support for debug events

- code/core/src/main/java/com/adobe/marketing/mobile/util/EventUtils.kt
- code/core/src/test/java/com/adobe/marketing/mobile/util/EventUtilsTest.kt
Switch Event extension functions to properties to be easier for access in Kotlin and parity with iOS. Java callers can still use
`EventUtils.getDebugEventSource(event)` , `EventUtils.getDebugEventType(event)`
> Switch Event extension functions to properties

- code/core/build.gradle
- code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java
- code/core/src/test/java/com/adobe/marketing/mobile/MobileCoreRobolectricTests.kt
- code/testapp-kotlin/src/main/AndroidManifest.xml
- code/testapp-kotlin/src/main/java/com/adobe/marketing/mobile/app/kotlin/BootBroadcastReceiver.kt
- code/testapp-kotlin/src/main/java/com/adobe/marketing/mobile/app/kotlin/MyApp.kt
Ported the Android 3.x change (https://github.com/adobe/aepsdk-core-android/pull/682) to Android 2.x.
> [Android 2.x] Do not initialize SDK in direct boot mode

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt
**Needs PM approval. DO NOT MERGE**
Currently a hack to apply an alpha of .99 on the content view holding the in-app message to ensure that corner radius settings are honored for API <=22.
However this is applied to all api levels currently. A very keen look show a faint outline the contents underneath the in-app message. Restrict the hack to API <=22 only to ensure that the issue is not seen on devices where the hack is not needed.
**Note that the slight transparency due to .99 alpha will still exist in API <=22 to honor rounded corner settings.**
Internal (MOB-21296)
Currently a hack to apply an alpha of .99 on the content view holding the in-app message to ensure that corner radius settings are honored for API <=22.
However this is applied to all api levels currently. A very keen look …
> Apply .99 alpha to versions <=22 only

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/Message.kt
Added dialog in case of UI take over for IAM , for making screen reader only read the content of IAM and not the UI beneath it.
Previously we were adding IAM directly in the activity UI, which, for screen readers, was just another content on the screen. So screen reader always read from top to bottom, regardless of IAM was showing or not. 
To make IAM getting read only while it is showing, we need to put it in a component which is a layer above the existing UI. So we chose to go with dialog with this. Also we have kept this behavior only in case of UI takeover is true, else it will block the direct interaction to UI beneath it.
https://jira.corp.adobe.com/browse/PLATIR-41103
Same as mentioned in description.
Tested for all the existing templates.
Ensured that non-ui take over case also …
> [PLATIR-41103] Added dialog for correct screen reader case

- code/core/api/core.api
- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/Presentation.kt
- code/core/src/main/java/com/adobe/marketing/mobile/services/ui/PresentationError.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/common/AEPPresentable.kt
- code/core/src/test/java/com/adobe/marketing/mobile/services/ui/common/AEPPresentableTest.kt
- rename `DelegateGateNotMet` to `SuppressedByAppDeveloper`.
- update conflict and suppressed by app developer error reasons to match the ones in-use on the iOS side
> add `SuppressedByAppDeveloper` to `PresentationError` interface

- code/core/api/core.api
- code/core/src/main/java/com/adobe/marketing/mobile/AdobeError.java
Adding new error codes for AdobeError.
These error codes are in parity with Error codes present in [AEPError](https://github.com/adobe/aepsdk-core-ios/blob/main/AEPCore/Sources/eventhub/AEPError.swift) for iOS.
> add new error codes for AdobeError

- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/DefaultInAppMessageEventHandler.kt
the coroutine children cancellation was causing all other coroutines other than the first to be cancelled early. this led to some race condition like behavior when determining if a presentable conflict had occurred. removing the children cancellation should have no effect on the event handling done in the `DefaultInAppMessageEventHandler`.
@prudrabhat did more in-depth investigation and his findings were:
> Earlier, each presentable was using its scope that was too heavy. Calling [cancel all children of the scope made sense](https://github.com/adobe/aepsdk-core-android/blob/main/code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/DefaultInAppMessageEventHandler.kt#L122) when it was in its own scope. Now all the UI Service is using the same scope. When 2 or more in-app …
> remove cancellation of coroutine children

- .circleci/config.yml
- Makefile
- code/core/build.gradle.kts
- code/settings.gradle.kts
- code/testutils/api/testutils.api
- code/testutils/build.gradle.kts
- code/testutils/src/main/AndroidManifest.xml
- code/testutils/src/main/java/com/adobe/marketing/mobile/MobileCoreHelper.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/services/MockDataStoreService.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/services/NetworkServiceHelper.kt
- code/testutils/src/main/java/com/adobe/marketing/mobile/services/ServiceProviderHelper.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/services/TestableNetworkRequest.kt
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/ADBCountDownLatch.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/FakeNamedCollection.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/JSONAsserts.kt
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/MockConnection.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/MockNetworkService.kt
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/MonitorExtension.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/NetworkRequestHelper.kt
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/NodeConfig.kt
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/RealNetworkService.kt
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/TestConstants.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/TestHelper.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/TestPersistenceHelper.java
- code/testutils/src/main/java/com/adobe/marketing/mobile/util/TestUtils.java
- code/testutils/src/test/java/com/adobe/marketing/mobile/util/JSONAssertsHelpersTests.kt
- code/testutils/src/test/java/com/adobe/marketing/mobile/util/JSONAssertsParameterizedTests.kt
- code/testutils/src/test/java/com/adobe/marketing/mobile/util/JSONAssertsPathOptionsTests.kt
- code/testutils/src/test/java/com/adobe/marketing/mobile/util/PathOptionElementCountTests.kt
- jitpack.yml
This PR transfers over AEPTestUtils to the Core repo as a separate module. At a high level the updates include:
1. Creation of new `testutils` module with current AEPTestUtils implementation from Android AEPTestUtils: https://github.com/timkimadobe/aepsdk-testutils-android
2. Gradle updates to:
1. Include testutils as a project module
2. Add AEPTestUtils to Core test and androidTest dependencies
3. Gradle config for AEPTestUtils
1. Include Core as a local project dependency
2. In `publishing`, add all other non-Core dependencies as Maven dependencies
4. Makefile updates
1. Add AEPTestUtil related make rules (excluding checkstyle)
5. API dump for AEPTestUtils - file created using gradle apiDump
All other new files are transfers from AEPTestUtils existing implementation (unchanged).
Tested …
> Transfer AEPTestUtils to Core

- code/core/src/phone/java/com/adobe/marketing/mobile/MobileCoreInitializer.kt
- code/core/src/test/java/com/adobe/marketing/mobile/MobileCoreRobolectricTests.kt
`UserManagerCompat.isUserUnlocked` currently crashes in OnePlus, Vivo, Motorola, and a few other devices. 
Implementing the workaround mentioned in https://issuetracker.google.com/issues/146535388 to fix the crash.
> [MOB-22844] Fix crash in direct boot mode detection

- code/core/build.gradle.kts
- code/core/src/phone/java/com/adobe/marketing/mobile/MobileCoreInitializer.kt
- code/core/src/test/java/com/adobe/marketing/mobile/MobileCoreInitializerTests.kt
Tracking lifecycle using ActivityLifecycleCallbacks requires the API to be called before the first onResume. This approach offers flexibility since ProcessLifecycleOwner always delivers the first lifecycle onResume when attaching the observer, if the app is in the foreground.
> Update automatic lifecycle tracking during simplified initialization to use ProcessLifecycleOwner

- code/core/src/androidTest/AndroidManifest.xml
- code/core/src/main/AndroidManifest.xml
- code/core/src/main/java/com/adobe/marketing/mobile/ExtensionDiscovery.kt
- code/identity/src/main/AndroidManifest.xml
- code/integration-tests/src/main/AndroidManifest.xml
- code/lifecycle/src/main/AndroidManifest.xml
- code/macrobenchmark/src/main/AndroidManifest.xml
- code/microbenchmark/src/androidTest/AndroidManifest.xml
- code/microbenchmark/src/main/AndroidManifest.xml
- code/signal/src/main/AndroidManifest.xml
- code/test-third-party-extension/src/main/AndroidManifest.xml
- code/testapp/src/main/AndroidManifest.xml
- code/testutils/src/main/AndroidManifest.xml
- Set android:exported=false for the `ExtensionDiscovery` service.
- Add license headers.
> Cleanup AndroidManifest.xml

- Makefile
- code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHub.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/MobileCore.java
- code/core/src/test/java/com/adobe/marketing/mobile/internal/eventhub/EventHubTests.kt
Some extensions don't want the request listener to time out when they call the API. They can achieve this by setting a large timeout. This is just a minor optimization to prevent adding additional timeout tasks for such listeners.
> Allow disabling timeout when registering response listener

- code/core/src/androidTest/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryTests.kt
- code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistory.kt
The current ordered event history lookup logic uses newest timestamp of the previous event as the from value to search the existence of next event in the events array, instead of the oldest timestamp. Content card disqualification will be using ordered event look up and is failing because of the incorrect implementation.
https://github.com/adobe/aepsdk-core-android/pull/749
The `historical` rule condition allows checking if a series of events occurred in a specific order in the SDK event history by providing the `searchType` as `ordered` . As per the spec, for `ordered` search type, "_Each provided event will be queried in order.  As long as the count of an event is greater than one, the subsequent event will be queried for using the oldest timestamp of the previous event.  If the end of …
> Fix ordered search type lookup in event history

- code/core/src/androidTest/java/com/adobe/marketing/mobile/internal/migration/V4MigratorTests.kt
- code/core/src/androidTest/java/com/adobe/marketing/mobile/internal/migration/V5LegacyCleanerTests.kt
- code/core/src/main/java/com/adobe/marketing/mobile/internal/migration/MigrationConstants.kt
- code/core/src/main/java/com/adobe/marketing/mobile/internal/migration/V4Migrator.kt
- code/core/src/main/java/com/adobe/marketing/mobile/internal/migration/V5LegacyCleaner.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/MobileCoreInitializer.kt
- code/core/src/test/java/com/adobe/marketing/mobile/MobileCoreInitializerTests.kt
- A new `V5LegacyCleaner` class was added to clean up legacy V5 Mobile Services data
- Mobile Services data migration code was removed from `V4Migrator.kt`
> Stop migrating Mobile Services datastore from v4 SDK

- code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequence.kt
- code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequenceTests.kt
- code/core/src/test/resources/rules_module_tests/consequence_rules_testSchemaInAppDetailSchema.json
Restore existing behavior of dispatching consequence in a rules response content event for `schema` type if the `detail` is not of type `https://ns.adobe.com/personalization/eventHistoryOperation`
For non event history write cases, we still need to dispatch the consequence so Messaging SDK can use it to display in-app message or content card
> Dispatch consequence in an rules consequence event if schema type is not eventHistory

- code/core/src/androidTest/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryDatabaseTests.kt
- code/core/src/androidTest/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryTests.kt
- code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryDatabase.kt
- code/core/src/main/java/com/adobe/marketing/mobile/internal/util/ListExtensions.kt
- code/core/src/main/java/com/adobe/marketing/mobile/internal/util/MapExtensions.kt
- code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequence.kt
- code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchTokenFinder.kt
- code/core/src/test/java/com/adobe/marketing/mobile/internal/util/ListExtensionsTests.kt
- code/core/src/test/java/com/adobe/marketing/mobile/internal/util/MapExtensionsTests.kt
- code/core/src/test/java/com/adobe/marketing/mobile/internal/util/MapUtilsTests.java
- code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesConsequenceTests.kt
- code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesEngineModuleTests.kt
- code/core/src/test/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchTokenFinderTest.kt
- code/core/src/test/resources/rules_module_tests/rules_testGroupLogicalOperatorsWithKeysEmbeddedInList.json
This PR enhances the map flattening logic to add support for nested lists and arrays.  The flattening logic in `MapExtensions.kt` has been updated to properly index list/array elements in the flattened keys and supports mixed data structures (maps containing lists, lists containing maps).
Before:
```kotlin
{rootKey: {key1: [value0, value1]}} -> {rootKey.key1: [value0, value1]}
```
After:
```kotlin
{rootKey: {key1: [value0, value1]}} -> {rootKey.key1.0: value0, rootKey.key1.1: value1}
```
This change affects how event data map is flattened in:
- Event data key lookup for rules `matcher` condition: Since key lookup in nested lists was never supported, this is a net new feature for this case and shouldn't create any backwards compatibility issues.
- Event data hash generation for event …
> Add support for nested lists to map flattening logic

- code/core/src/androidTest/java/com/adobe/marketing/mobile/services/ui/message/views/MessageScreenTests.kt
- code/core/src/phone/java/com/adobe/marketing/mobile/services/ui/message/views/MessageFrame.kt
**Problem**
Inset calculation for in-app messages has regressed in `v3.1.1-core`.
The`MessageOffsetMapper` methods expect the full screen view dimensions as the third parameter to calculate the offset percentage correctly, but now being calculated incorrectly according to the dimensions of the in-app message rather than the dimensions of the view. 
```
val horizontalOffset = MessageOffsetMapper.getHorizontalOffset(
inAppMessageSettings.horizontalAlignment,
inAppMessageSettings.horizontalInset,
widthDp.value  // ❌ This is the MESSAGE width, not content view/screen width
)
val verticalOffset = MessageOffsetMapper.getVerticalOffset(
inAppMessageSettings.verticalAlignment,
inAppMessageSettings.verticalInset,
heightDp.value  // ❌ This is the MESSAGE height, not content view/screen height
)
``` …
> Fix message inset calculation for InAppMessages

- code/build.gradle.kts
AEP Gradle Plugin fixes project version generation for bundles. This allows projects with multiple modules to set the right version tag without overwriting on publish.
> Use AEP Gradle Plugin 3.4.1
